# Generated by Django 3.2.6 on 2021-11-30 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=64)),
                ('crop_image', models.URLField(default='')),
                ('crop_quantity', models.IntegerField()),
                ('crop_info', models.TextField()),
                ('crop_date', models.DateTimeField(default='2021-11-30 03:26[:24[. 412919]]')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.categories')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
