# Generated by Django 3.2.6 on 2021-12-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='crop_date',
            field=models.DateTimeField(),
        ),
    ]
